version: '3.8'

services:
  db:
    image: postgres:15
    container_name: tictactoe-db
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - tictactoe-data:/var/lib/postgresql/data
    networks:
      - tictactoe-network

  # app:
  #   image: tictactoe-app
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - tictactoe-network

volumes:
  tictactoe-data:

networks:
  tictactoe-network:
