services:
  db:
    image: postgres:15
    container_name: tictactoe-db
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - tictactoe-data:/var/lib/postgresql/data
    networks:
      - tictactoe-network

  server:
    build:
      context: ./tictactoe-backend
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./tictactoe-backend/src/main/resources/application.properties:/app/application.properties
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - tictactoe-network
  app:
    build:
      context: ./tictactoe-app
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    env_file:
      - .env
    ports:
      - "3000:80"   # maps nginx inside container (80) to host 3000
    depends_on:
      - server
    networks:
      - tictactoe-network

volumes:
  tictactoe-data:

networks:
  tictactoe-network:
